---
- name: DotFiles Config
  hosts: localhost
  connection: local
  vars_prompt:
    - name: ansible_become_pass
      prompt: "BECOME password"
      private: true
      default: ""
  vars:
    includes:
      - tasks/homebrew.yml
      - tasks/zsh.yml
      - tasks/git.yml
      - tasks/ssh.yml
      - tasks/java.yml
      - tasks/android_studio.yml
      - tasks/zed.yml
      - tasks/ghostty.yml
      - tasks/aerospace.yml
      - tasks/claude.yml
      - tasks/mac_defaults.yml

  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: Execute playbook
      block:
        - name: Create directory for sudo_askpass
          ansible.builtin.file:
            path: "{{ playbook_dir }}/.ansible/bin"
            state: directory
            mode: '0700'

        - name: Create script for sudo_askpass
          ansible.builtin.template:
            src: templates/sudo_askpass.sh.j2
            dest: "{{ playbook_dir }}/.ansible/bin/sudo_askpass.sh"
            mode: '0700'

        - name: Run included tasks
          ansible.builtin.include_tasks: "{{ item }}"
          loop: "{{ includes }}"
      always:
        - name: Clean up askpass helper script
          ansible.builtin.file:
            path: "{{ playbook_dir }}/.ansible/bin/sudo_askpass.sh"
            state: absent