---
- name: DotFiles Config
  hosts: localhost
  connection: local
  vars:
    includes:
      - tasks/homebrew.yml
      - tasks/zsh.yml
      - tasks/git.yml
      - tasks/ssh.yml
      - tasks/java.yml
      - tasks/android_studio.yml
      - tasks/ghostty.yml
      - tasks/aerospace.yml
      - tasks/mac_defaults.yml

  pre_tasks:
    - name: Detect Host User
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: Run included tasks
      ansible.builtin.include_tasks: "{{ item }}"
      loop: "{{ includes }}"
