---
- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Set git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"
  no_log: true

- name: Set git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

- name: Set user.signingkey
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ ansible_user_dir }}/.ssh/id_ed25519.pub"

- name: Set gpg.format
  community.general.git_config:
    name: gpg.format
    scope: global
    value: ssh

- name: Set commit.gpgsign
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: Set tag.gpgsign
  community.general.git_config:
    name: tag.gpgsign
    scope: global
    value: true