---
- name: Ensure zsh is installed
  homebrew:
    name: "zsh"
    state: present

- name: Ensure zsh is the default shell
  user:
    name: "{{ host_user }}"
    shell: "/opt/homebrew/bin/zsh"
  become: true

- name: Ensure powerlevel10k theme is installed
  homebrew:
    name: "powerlevel10k"

- name: Ensure font-jetbrains-mono-nerd-font is installed
  homebrew_cask:
    name: "font-jetbrains-mono-nerd-font"

- name: Ensure zsh-autosuggestions plugin is installed
  homebrew:
    name: "zsh-autosuggestions"

- name: Ensure zsh-syntax-highlighting plugin is installed
  homebrew:
    name: "zsh-syntax-highlighting"

- name: Create symlink for .zshrc file
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    force: true
    state: link

- name: Create symlink for .p10k.zsh file
  ansible.builtin.file:
    src: "{{ role_path }}/files/.p10k.zsh"
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    state: link

- name: Add dotfiles to path
  blockinfile:
    block: |
      path+=({{ ansible_user_dir }}/.dotfiles/bin)
    create: true
    marker: "# {mark} Ansible managed block for custom dotfiles.sh script"
    mode: 0644
    path: "{{ ansible_user_dir }}/.zshenv"
