---
- name: Ensure zsh is installed
  homebrew:
    name: "zsh"
    state: present

- name: Ensure zsh is the default shell
  user:
    name: "{{ host_user }}"
    shell: "/opt/homebrew/bin/zsh"
  become: true

- name: Ensure powerlevel10k theme is installed
  homebrew:
    name: "powerlevel10k"

- name: Ensure font-jetbrains-mono-nerd-font is installed
  homebrew_cask:
    name: "font-jetbrains-mono-nerd-font"

- name: Ensure zsh-autosuggestions plugin is installed
  homebrew:
    name: "zsh-autosuggestions"

- name: Ensure zsh-syntax-highlighting plugin is installed
  homebrew:
    name: "zsh-syntax-highlighting"

- name: Copy .zshrc file
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"

- name: Copy .p10k.zsh file
  ansible.builtin.copy:
    src: ".p10k.zsh"
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    mode: "0644"
