import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Full"

opacity = 0.7
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "MediumItalic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 14
