---
- name: Ensure zsh is installed
  homebrew:
    name: "zsh"
    state: present

- name: Ensure zsh is the default shell
  user:
    name: "{{ host_user }}"
    shell: "/opt/homebrew/bin/zsh"
  become: true

- name: Check if oh-my-zsh is installed
  stat:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
  register: ohmyzsh_file

- name: Download Oh My Zsh installation script
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/install_ohmyzsh.sh
  when: not ohmyzsh_file.stat.exists

- name: Run Oh My Zsh installation script
  command: sh /tmp/install_ohmyzsh.sh --unattended
  register: ohmyzsh_result
  failed_when: "'FAILED' in ohmyzsh_result.stderr"
  when: not ohmyzsh_file.stat.exists

- name: Clone powerlevel10k theme
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ zsh_custom }}/themes/powerlevel10k"
    clone: yes

- name: Clone fast-syntax-highlighting plugin
  ansible.builtin.git:
    repo: https://github.com/zdharma-continuum/fast-syntax-highlighting.git
    dest: "{{ zsh_custom }}/plugins/fast-syntax-highlighting"
    clone: yes

- name: Clone zsh-autosuggestions plugin
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
    clone: yes

- name: Ensure meslo font is installed
  homebrew_cask:
    name: font-meslo-for-powerlevel10k
    state: present

- name: Copy .zshrc
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"

- name: Copy .p10k.zsh
  ansible.builtin.copy:
    src: ".p10k.zsh"
    dest: "{{ ansible_user_dir }}/.p10k.zsh"
    mode: "0644"

- name: Add dotfiles to path
  blockinfile:
    block: |
      path+=({{ ansible_user_dir }}/.dotfiles/bin)
    create: true
    marker: "# {mark} Ansible managed block for custom dotfiles.sh script"
    mode: 0644
    path: ~/.zshenv
