---
- name: Ensure iterm2 is installed
  homebrew_cask:
    name: "iterm2"
    state: present

- name: "Copy dynamic profiles file"
  ansible.builtin.copy:
    src: "Profiles.json"
    dest: "{{ ansible_user_dir }}/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json"

- name: Ensure configured profile is set to default.
  command: "defaults write com.googlecode.iterm2 'Default Bookmark Guid' -string '62C7A3CE-D73E-4406-8A56-5CBA68505935'"
