---
- name: Ensure openjdk 17 is installed
  homebrew:
    name: "openjdk@17"
    state: present
  register: jdk_installed

- name: Set JAVA_HOME if JDK was installed
  blockinfile:
    block: |
      export JAVA_HOME="$(find /opt/homebrew/Cellar/openjdk@17/* -type d -prune)"
      export JDK_HOME="$(find /opt/homebrew/Cellar/openjdk@17/* -type d -prune)"
    create: true
    marker: "# {mark} Ansible managed block for JDK"
    mode: 0644
    path: "{{ ansible_user_dir }}/.zshenv"
  when: jdk_installed is succeeded

- name: Print java home
  shell: echo "$(find /opt/homebrew/Cellar/openjdk@17/* -type d -prune)"
  register: java_location

- name: Set JAVA_HOME fact
  set_fact:
    JAVA_HOME: "{{ java_location.stdout }}"
