---
- name: Ensure alacritty is installed
  homebrew_cask:
    name: "alacritty"
    state: present

- name: Ensure alacritty config folder exists
  file:
    path: "{{ ansible_user_dir }}/.config/alacritty"
    state: directory
    mode: 0700

- name: Ensure alacritty themes folder exists
  file:
    path: "{{ ansible_user_dir }}/.config/alacritty/themes"
    state: directory
    mode: 0700

- name: Clone alacritty themes
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty-theme
    dest: "{{ ansible_user_dir }}/.config/alacritty/themes"
    clone: yes

- name: Create symlink for alacritty config file
  ansible.builtin.file:
    src: "{{ role_path }}/files/alacritty.toml"
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.toml"
    state: link
